/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLLD_Gui;

import Connection.ConnectSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.io.IOException;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import QLLD_DTO.CongTrinh;
import QLLD_DAO.CongTrinh_DAO;
import QLLD_DAO.CongNhan_DAO;
import QLLD_DAO.PhanCong_DAO;
import Connection.ConnectSQL;
import static Connection.ConnectSQL.con;
import QLLD_DTO.CongNhan;
import QLLD_DTO.PhanCong;
import custom.MyTable;
import java.awt.event.ItemEvent;

/**
 *
 * @author Admin
 */
public class PhanCongCN extends javax.swing.JPanel {

    CongNhan_DAO daoCT = new CongNhan_DAO();
    PhanCong_DAO dsPC = new PhanCong_DAO();
    private ArrayList<CongNhan> listCongNhan = daoCT.docTuBang();
    private DefaultTableModel dataModelDSCT = new DefaultTableModel();
    private DefaultTableModel dataModelPC = new DefaultTableModel();

    /**
     * Creates new form ChamCongNVHC
     */
    public PhanCongCN() {
        initComponents();

        dataModelDSCT = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Công Trình", "Tên Công Trình",}
        );
        TableDSCongTrinh.setModel(dataModelDSCT);

        dataModelPC = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Công Nhân", "Tên Công Nhân", "Mã Phân Công", "Tên Công Trình", "Mã Công Trình"
                }
        );
        TableDSPhanCong.setModel(dataModelPC);

        getDataMaCN();
//        ConnectSQL.getInstance().connect();
        updateTableDataDSCT();
        updateTableDataPC();
        updateComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhanCong = new javax.swing.JLabel();
        PanelThongTinPhanCong = new javax.swing.JPanel();
        lblMaCongNhan = new javax.swing.JLabel();
        lblTenCongTrinh = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTenCongNhan = new javax.swing.JLabel();
        cboMaCN = new javax.swing.JComboBox<>();
        txtTenCN = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        lblMaCongTrinh = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        lblMaPhanCong = new javax.swing.JLabel();
        txtTenCongTrinh = new javax.swing.JTextField();
        txtMaPhanCong = new javax.swing.JTextField();
        txtMaCongTrinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDSCongTrinh = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDSPhanCong = new MyTable();
        ;
        PanelNorth = new javax.swing.JPanel();
        PanelLamMoiMaPhanCong = new javax.swing.JPanel();
        btnLamMoiMaPhanCong = new javax.swing.JButton();
        PanelXoa = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        PanelPhanCong = new javax.swing.JPanel();
        btnPhanCong = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        lblPhanCong.setBackground(new java.awt.Color(255, 255, 255));
        lblPhanCong.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPhanCong.setForeground(new java.awt.Color(51, 51, 255));
        lblPhanCong.setText("PHÂN CÔNG");
        lblPhanCong.setOpaque(true);

        PanelThongTinPhanCong.setBackground(new java.awt.Color(204, 204, 204));
        PanelThongTinPhanCong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phân công", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        lblMaCongNhan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaCongNhan.setText("Mã công nhân");

        lblTenCongTrinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTenCongTrinh.setText("Tên công trình:");

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTenCongNhan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTenCongNhan.setText("Tên công nhân");

        cboMaCN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtTenCN.setEnabled(false);
        txtTenCN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblTenSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTenSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenSPMouseClicked(evt);
            }
        });
        lblTenSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblTenSPKeyReleased(evt);
            }
        });

        lblMaCongTrinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaCongTrinh.setText(" Mã công trình :");

        lblMaSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblMaPhanCong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaPhanCong.setText("Mã phân công");

        txtTenCongTrinh.setEnabled(false);
        txtTenCongTrinh.setEditable(false);

        javax.swing.GroupLayout PanelThongTinPhanCongLayout = new javax.swing.GroupLayout(PanelThongTinPhanCong);
        PanelThongTinPhanCong.setLayout(PanelThongTinPhanCongLayout);
        PanelThongTinPhanCongLayout.setHorizontalGroup(
            PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaPhanCong, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                        .addComponent(lblTenCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenCN)))
                .addGap(112, 112, 112)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenCongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaCongTrinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenCongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaCongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelThongTinPhanCongLayout.setVerticalGroup(
            PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaCongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenCongNhan)
                            .addComponent(txtTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTenCongTrinh)
                                .addComponent(txtTenCongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaPhanCong)))
                    .addGroup(PanelThongTinPhanCongLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelThongTinPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMaCongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaCongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableDSCongTrinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Công Trình", "Tên Công Trình"
            }
        ));
        TableDSCongTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDSCongTrinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDSCongTrinh);

        TableDSPhanCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CN", "Tên CN", "Mã phân công", "Mã công trình", "Tên công trình"
            }
        ));
        TableDSPhanCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDSPhanCongMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableDSPhanCongMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TableDSPhanCong);

        PanelNorth.setBackground(new java.awt.Color(255, 255, 255));
        PanelNorth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), java.awt.Color.blue)); // NOI18N

        PanelLamMoiMaPhanCong.setBackground(new java.awt.Color(255, 255, 255));

        btnLamMoiMaPhanCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sua.png"))); // NOI18N
        btnLamMoiMaPhanCong.setText("Làm Mới Mã Phân Công");
        btnLamMoiMaPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiMaPhanCongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLamMoiMaPhanCongLayout = new javax.swing.GroupLayout(PanelLamMoiMaPhanCong);
        PanelLamMoiMaPhanCong.setLayout(PanelLamMoiMaPhanCongLayout);
        PanelLamMoiMaPhanCongLayout.setHorizontalGroup(
            PanelLamMoiMaPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLamMoiMaPhanCongLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLamMoiMaPhanCong)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        PanelLamMoiMaPhanCongLayout.setVerticalGroup(
            PanelLamMoiMaPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLamMoiMaPhanCongLayout.createSequentialGroup()
                .addComponent(btnLamMoiMaPhanCong)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelXoa.setBackground(new java.awt.Color(255, 255, 255));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/xoaaa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelXoaLayout = new javax.swing.GroupLayout(PanelXoa);
        PanelXoa.setLayout(PanelXoaLayout);
        PanelXoaLayout.setHorizontalGroup(
            PanelXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelXoaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnXoa)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PanelXoaLayout.setVerticalGroup(
            PanelXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelXoaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnXoa))
        );

        PanelPhanCong.setBackground(new java.awt.Color(255, 255, 255));

        btnPhanCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/themm.png"))); // NOI18N
        btnPhanCong.setText("Phân Công");
        btnPhanCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanCongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPhanCongLayout = new javax.swing.GroupLayout(PanelPhanCong);
        PanelPhanCong.setLayout(PanelPhanCongLayout);
        PanelPhanCongLayout.setHorizontalGroup(
            PanelPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPhanCongLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnPhanCong)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelPhanCongLayout.setVerticalGroup(
            PanelPhanCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPhanCongLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPhanCong))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout PanelNorthLayout = new javax.swing.GroupLayout(PanelNorth);
        PanelNorth.setLayout(PanelNorthLayout);
        PanelNorthLayout.setHorizontalGroup(
            PanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelLamMoiMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNorthLayout.setVerticalGroup(
            PanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(PanelXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelNorthLayout.createSequentialGroup()
                .addGroup(PanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelNorthLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(PanelLamMoiMaPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPhanCong)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(PanelNorth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(PanelThongTinPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPhanCong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelNorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(PanelThongTinPhanCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TableDSCongTrinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSCongTrinhMouseClicked
        int i = TableDSCongTrinh.getSelectedRow();
        TableModel model = TableDSCongTrinh.getModel();
        txtMaCongTrinh.setText(model.getValueAt(i, 0).toString());
        txtTenCongTrinh.setText(model.getValueAt(i, 1).toString());
    }//GEN-LAST:event_TableDSCongTrinhMouseClicked

    private void lblTenSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTenSPKeyReleased

    }//GEN-LAST:event_lblTenSPKeyReleased

    private void lblTenSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenSPMouseClicked

    }//GEN-LAST:event_lblTenSPMouseClicked

    private void TableDSPhanCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSPhanCongMouseClicked
//        int row = TableDSPhanCong.getSelectedRow();
//        cboMaCN.setSelectedItem(TableDSPhanCong.getValueAt(row, 1));
//        txtTenCN.setText(TableDSPhanCong.getValueAt(row, 2).toString());
//        txtMaPhanCong.setText(TableDSPhanCong.getValueAt(row, 3).toString());
//
//        txtTenCongTrinh.setText(TableDSPhanCong.getValueAt(row, 4).toString());
//        cboMaCT.setSelectedItem(TableDSPhanCong.getValueAt(row, 5));


    }//GEN-LAST:event_TableDSPhanCongMouseClicked

    private void TableDSPhanCongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSPhanCongMouseReleased

    }//GEN-LAST:event_TableDSPhanCongMouseReleased
    private PhanCong revertPCFormTextFile() {
        int maCN;
        maCN = Integer.parseInt(cboMaCN.getSelectedItem().toString());
        String tenCN = txtTenCN.getText().toString();
        String tenCongTrinh = txtTenCongTrinh.getText().toString();
        String maCongTrinh = txtMaCongTrinh.getText().toString();
        String maPC = txtMaPhanCong.getText().toString();
        if (!maPC.matches("PC\\d{3}")) {
            JOptionPane.showMessageDialog(null, "Mã phân công không đúng định dạng", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        if (tenCN.isEmpty() || tenCongTrinh.isEmpty() || maCongTrinh.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống các trường", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        return new PhanCong(maCN, tenCN, maPC, tenCongTrinh, maCongTrinh);
    }


    private void btnPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanCongActionPerformed

        try {
            PhanCong pc = revertPCFormTextFile();
            if (dsPC.create(pc)) {
                Object[] rowData = {String.valueOf(pc.getMaCN()), pc.getTenCN(), pc.getMaPC(), pc.getTenCongTrinh(), pc.getMaCongTrinh()};
                dataModelPC.addRow(rowData);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnPhanCongActionPerformed
    private void xoaRongTextfields() {
        cboMaCN.setSelectedIndex(0);
        txtTenCN.setText("");
        txtTenCongTrinh.setText("");
        txtMaCongTrinh.setText("");
        txtMaPhanCong.setText("");
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = TableDSPhanCong.getSelectedRow();
        if (row >= 0) {
            String maPC = TableDSPhanCong.getValueAt(row, 2).toString();
            if (dsPC.delete(maPC)) {
                dataModelPC.removeRow(row);
                xoaRongTextfields();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiMaPhanCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiMaPhanCongActionPerformed
        txtMaPhanCong.setText("");
    }//GEN-LAST:event_btnLamMoiMaPhanCongActionPerformed

//Lấy danh sách công nhân theo mã 
    private void getDataMaCN() {
        for (int i = 0; i < listCongNhan.size(); i++) {
            if (listCongNhan.get(i).getChucVu().equals("Công Nhân")) {
                cboMaCN.addItem(String.valueOf(listCongNhan.get(i).getMaCN()));
            }
        }
    }

    private void updateTableDataPC() {
        PhanCong_DAO ds = new PhanCong_DAO();
        List<PhanCong> list = ds.docTuBang();
        for (PhanCong pc : list) {
            String[] rowData = {String.valueOf(pc.getMaCN()), pc.getTenCN(), pc.getMaPC(), pc.getTenCongTrinh(), pc.getMaCongTrinh()};
            dataModelPC.addRow(rowData);
        }
        TableDSPhanCong.setModel(dataModelPC);
    }

    private void updateTableDataDSCT() {
        CongTrinh_DAO daoct = new CongTrinh_DAO();
        List<CongTrinh> listCT = daoct.docTubang();
        for (CongTrinh ct : listCT) {
            String[] rowData = {ct.getMaCongTrinh(), ct.getTenCongTrinh()};
            dataModelDSCT.addRow(rowData);
        }
        TableDSCongTrinh.setModel(dataModelDSCT);
    }

    private void updateComboBox() {
        CongNhan_DAO ds = new CongNhan_DAO();
        List<CongNhan> list = ds.docTuBang();
        cboMaCN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(ItemEvent arg0) {
                if (arg0.getStateChange() == ItemEvent.SELECTED) {
                    int selectedMaNV = Integer.parseInt(cboMaCN.getSelectedItem().toString());
                    // tìm kiếm công nhân tương ứng với mã công nhân
                    CongNhan selectedCongNhan = null;
                    for (CongNhan cn : list) {
                        int maCN = cn.getMaCN();
                        if (maCN == selectedMaNV) {
                            selectedCongNhan = cn;
                            break;
                        }
                    }
                    if (selectedCongNhan != null) {
                        // hiển thị tên công nhân tương ứng
                        txtTenCN.setText(selectedCongNhan.getTenCN());
                    }
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLamMoiMaPhanCong;
    private javax.swing.JPanel PanelNorth;
    private javax.swing.JPanel PanelPhanCong;
    private javax.swing.JPanel PanelThongTinPhanCong;
    private javax.swing.JPanel PanelXoa;
    private javax.swing.JTable TableDSCongTrinh;
    private javax.swing.JTable TableDSPhanCong;
    private javax.swing.JButton btnLamMoiMaPhanCong;
    private javax.swing.JButton btnPhanCong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaCN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblMaCongNhan;
    private javax.swing.JLabel lblMaCongTrinh;
    private javax.swing.JLabel lblMaPhanCong;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblPhanCong;
    private javax.swing.JLabel lblTenCongNhan;
    private javax.swing.JLabel lblTenCongTrinh;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JTextField txtMaCongTrinh;
    private javax.swing.JTextField txtMaPhanCong;
    private javax.swing.JTextField txtTenCN;
    private javax.swing.JTextField txtTenCongTrinh;
    // End of variables declaration//GEN-END:variables
}
