/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLLD_Gui;

import QLLD_DAO.CongNhan_DAO;
import QLLD_DAO.CongTrinh_DAO;
import QLLD_DAO.NguoiQuanLiCongTrinh_DAO;
import QLLD_DTO.CongNhan;
import QLLD_DTO.nguoiQuanLiCongTrinh;
import QLLD_DTO.CongTrinh;
import custom.MyTable;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.util.SimpleAnnotationValueVisitor14;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QuanLyCongTrinh extends javax.swing.JPanel {

    private DefaultTableModel dataModel;
    CongTrinh_DAO dSCT = new CongTrinh_DAO();
    List<QLLD_DTO.nguoiQuanLiCongTrinh> dsNQL = new NguoiQuanLiCongTrinh_DAO().docTuBang();
    Connection conn;
    ResultSet rs;

    /**
     * Creates new form CapNhatNVHC
     */
    public QuanLyCongTrinh() {
        initComponents();
        dataModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Hợp Đồng", "Mã Công Trình", "Tên Công Trình", "Mã Nhân Viên", "Tên Nhân Viên", "Ngày Lập", "Ngày Hoàn Thành", "Tổng Giá Trị Hợp Đồng"
                }
        );
        jTableHD.setModel(dataModel);
        updateComboBox();
        updateTableData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHD = new MyTable();
        ;
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnSua = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        lblMaHSLNVHC = new javax.swing.JLabel();
        lblHSLNVHC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayThanhLy = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        txtNgayKy = new com.toedter.calendar.JDateChooser();
        lblHSLNVHC1 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        lblHSLNVHC2 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        lblHSLNVHC4 = new javax.swing.JLabel();
        cboMaNV = new javax.swing.JComboBox<>();
        lblHSLNVHC5 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÝ CÔNG TRÌNH");
        jLabel1.setOpaque(true);

        jTableHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hợp Đồng", "Mã Công Trình", "Tên Công Trình", "Mã Quản Lý", "Tên Quản Lý", "Ngày Lập", "Ngày Hoàn Thành", "Tổng Giá Trị Hợp Đồng"
            }
        ));
        jTableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHD);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), java.awt.Color.blue)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnSua.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sua.png"))); // NOI18N
        btnSua.setText("        Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnXoa.setBackground(new java.awt.Color(204, 0, 255));
        btnXoa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/xoaaa.png"))); // NOI18N
        btnXoa.setText("        Xóa");
        btnXoa.setName(""); // NOI18N
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(0, 204, 204));
        btnThem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/themm.png"))); // NOI18N
        btnThem.setText("       Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(899, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hợp đồng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        lblMaHSLNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaHSLNVHC.setText("Ngày ký");

        lblHSLNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHSLNVHC.setText("Mã hợp đồng");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Ngày hoàn thành");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Tổng giá trị hợp đồng");

        txtGiaTri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTriActionPerformed(evt);
            }
        });

        txtMaHD.setEnabled(true);
        txtMaHD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaHD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        lblHSLNVHC1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHSLNVHC1.setText("Tên công trình");

        txtTenKH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        lblHSLNVHC2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHSLNVHC2.setText("Tên Người Quản Lý");

        txtTenNV.setEnabled(false);
        txtTenNV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        lblHSLNVHC4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHSLNVHC4.setText("Mã Người Quản Lý");

        cboMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaNVActionPerformed(evt);
            }
        });

        lblHSLNVHC5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHSLNVHC5.setText("Mã công trình");

        txtMaSP.setEnabled(true);
        txtMaSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHSLNVHC5)
                        .addGap(70, 70, 70)
                        .addComponent(txtMaSP))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblHSLNVHC)
                                    .addGap(70, 70, 70))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblMaHSLNVHC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNgayKy, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboMaNV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblHSLNVHC4)))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHSLNVHC1)
                            .addComponent(lblHSLNVHC2))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtTenKH)
                    .addComponent(txtNgayThanhLy, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHSLNVHC)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHSLNVHC1)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHSLNVHC4)
                            .addComponent(lblHSLNVHC2)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaHSLNVHC)
                            .addComponent(txtNgayKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(txtNgayThanhLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHSLNVHC5)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Bảng danh sách hợp đồng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(584, 584, 584))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed

    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtGiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTriActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNVActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void cboMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaNVActionPerformed
//       CongTrinh ct = reverSPFormTextFile();
//       if(ct.)
    }//GEN-LAST:event_cboMaNVActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        CongTrinh lh = reverSPFormTextFile();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String selectedDateString = dateFormat.format(txtNgayKy.getDate());
        String selectDate = dateFormat.format(txtNgayThanhLy.getDate());
        String maCT = txtMaSP.getText();
        if (dSCT.checktrungma(maCT)) {
            JOptionPane.showMessageDialog(null, "Mã công trình đã tồn tại");
        } else {
            try {
                if (dSCT.create(lh)) {
                    Object[] rowData = {txtMaHD.getText(), txtMaSP.getText(), txtTenKH.getText(), cboMaNV.getSelectedItem().toString(), txtTenNV.getText(), selectedDateString, selectDate, txtGiaTri.getText()};
                    dataModel.addRow(rowData);
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                }
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyCongTrinh.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Thêm không thành công");
            }
            updateTableData();
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        int row = jTableHD.getSelectedRow();
        if (row >= 0) {
            String maCongTrinh = (String) jTableHD.getValueAt(row, 1);
            if (dSCT.delete(maCongTrinh)) {
                dataModel.removeRow(row);
                JOptionPane.showMessageDialog(null, "Xóa thành công");
            }else{
                JOptionPane.showMessageDialog(null, "Xóa không thành công");
            }
        }
        
//        updateTableData();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        int row = jTableHD.getSelectedRow();
        if (row >= 0) {
            CongTrinh lh = reverSPFormTextFile();
            try {
                if (dSCT.update(lh)) {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                    String dateSelectKi = dateFormat.format(txtNgayKy.getDate()); // Chuyển đổi ngày tháng sang chuỗi String
                    String dateSelect = dateFormat.format(txtNgayThanhLy.getDate()); // Chuyển đổi ngày tháng sang chuỗi String
                    DecimalFormat decimalFormat = new DecimalFormat("#,### VND"); // Format the value of tongGTri
                    String formattedTongGTri = decimalFormat.format(lh.getTongGiaTriHopDong());
                    jTableHD.setValueAt(txtMaHD.getText(), row, 0);
                    jTableHD.setValueAt(txtMaSP.getText(), row, 1);
                    jTableHD.setValueAt(txtTenKH.getText(), row, 2);
                    String selectedMaNV = cboMaNV.getSelectedItem().toString();
                    nguoiQuanLiCongTrinh selectedNQLCT = null;
                    for (nguoiQuanLiCongTrinh nqlct : dsNQL) {
                        String maQLY = String.valueOf(nqlct.getMaQuanLy());
                        if (maQLY.equals(selectedMaNV)) {
                            selectedNQLCT = nqlct;
                            break;
                        }
                    }
                    if (selectedNQLCT != null) {
                        jTableHD.setValueAt(selectedMaNV, row, 3);
                        jTableHD.setValueAt(selectedNQLCT.getTenQuanLy(), row, 4);
                    }
                    jTableHD.setValueAt(dateSelectKi, row, 5);
                    jTableHD.setValueAt(dateSelect, row, 6);
                    jTableHD.setValueAt(formattedTongGTri, row, 7);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                } else {
                    JOptionPane.showMessageDialog(null, "Không sửa được");
                }
            } catch (ParseException ex) {
                Logger.getLogger(QuanLyCongTrinh.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        updateTableData();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void jTableHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDMouseClicked
        int row = jTableHD.getSelectedRow();
        txtMaHD.setText(jTableHD.getValueAt(row, 0).toString());
        txtMaSP.setText(jTableHD.getValueAt(row, 1).toString());
        txtTenKH.setText(jTableHD.getValueAt(row, 2).toString());
        cboMaNV.setSelectedItem(jTableHD.getValueAt(row, 3).toString());
        txtTenNV.setText(jTableHD.getValueAt(row, 4).toString());
        try {
            String ngayKyString = jTableHD.getValueAt(row, 5).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date ngayKyDate = dateFormat.parse(ngayKyString);
            SimpleDateFormat newDateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String ngayKyFormatted = newDateFormat.format(ngayKyDate);
            txtNgayKy.setDate(newDateFormat.parse(ngayKyFormatted));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        try {
            String ngayHTString = jTableHD.getValueAt(row, 6).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date ngayHTDate = dateFormat.parse(ngayHTString);
            SimpleDateFormat newDateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String ngayHTFormatted = newDateFormat.format(ngayHTDate);
            txtNgayThanhLy.setDate(newDateFormat.parse(ngayHTFormatted));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        String tongGTriString = jTableHD.getValueAt(row, 7).toString().replaceAll("[^\\d]", "");
        long tongGTri = Long.parseLong(tongGTriString);
        txtGiaTri.setText(String.valueOf(tongGTri));
    }//GEN-LAST:event_jTableHDMouseClicked

    private void updateTableData() {
        CongTrinh_DAO ds = new CongTrinh_DAO();
        List<CongTrinh> list = ds.docTubang();
        dataModel.setRowCount(0); // Xóa toàn bộ dữ liệu hiện có trong bảng
        for (CongTrinh s : list) {
            String formattedGiaTri = new DecimalFormat("#,### VND").format(s.getTongGiaTriHopDong()); // Format the value of tongGiaTriHopDong
            String[] rowData = {s.getMaHopDong(), s.getMaCongTrinh(), s.getTenCongTrinh(), s.getnQLCT() + "", s.getTenNhanVien(), s.getNgayKi(), s.getNgayHoanThanh(), formattedGiaTri};
            dataModel.addRow(rowData);
        }
        jTableHD.scrollRectToVisible(jTableHD.getCellRect(jTableHD.getRowCount() - 1, 0, false)); // Cuộn tới dòng mới nhất

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JComboBox<String> cboMaNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableHD;
    private javax.swing.JLabel lblHSLNVHC;
    private javax.swing.JLabel lblHSLNVHC1;
    private javax.swing.JLabel lblHSLNVHC2;
    private javax.swing.JLabel lblHSLNVHC4;
    private javax.swing.JLabel lblHSLNVHC5;
    private javax.swing.JLabel lblMaHSLNVHC;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaSP;
    private com.toedter.calendar.JDateChooser txtNgayKy;
    private com.toedter.calendar.JDateChooser txtNgayThanhLy;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables

    private CongTrinh reverSPFormTextFile() {
        String maHD = txtMaHD.getText();
        String maCongTrinh = txtMaSP.getText().toString();
        String tenCongTrinh = txtTenKH.getText().toString();
        String maNV = cboMaNV.getSelectedItem().toString();
        String tenNV = txtTenNV.getText().toString();
        // Định dạng chuỗi kết quả
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        Date ngayKy = txtNgayKy.getDate();
        Date ngayHT = txtNgayThanhLy.getDate();
        String ngayKyString = sdf.format(ngayKy);
        String ngayHTString = sdf.format(ngayHT);
        // Xóa các ký tự không phải s
        String giaTriString = txtGiaTri.getText().replaceAll("[^\\d]", "");
        long tongGTri = Long.parseLong(giaTriString);
        System.err.println(tongGTri + "rs");
        //Kiem tra du lieu
        if (!maHD.matches("^HD\\d{3}$")) {
            JOptionPane.showMessageDialog(null, "Mã hợp đồng phải bắt đầu bằng HD theo sau là 3 chữ số", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (!maCongTrinh.matches("^CT\\d{3}$")&&!dSCT.checktrungma(txtMaSP.getText()))  {
                JOptionPane.showMessageDialog(null, "Mã Công Trình phải bắt đầu bằng CT theo sau là 3 chữ số", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                
            return null;
        }

        return new CongTrinh(maCongTrinh, tenCongTrinh, ngayHTString, maHD, ngayKyString, new nguoiQuanLiCongTrinh(maNV), tenNV, tongGTri);
    }

    private void updateComboBox() {
        CongNhan_DAO ds = new CongNhan_DAO();
        List<CongNhan> list = ds.docTuBang();
        for (CongNhan cn : list) {

            if (cn.getChucVu().equals("Quản Lý Công Trình")) {
                cboMaNV.addItem(String.valueOf(cn.getMaCN()));
                System.err.println(cn.getMaCN());
            }
        }
        cboMaNV.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent arg0) {
                if (arg0.getStateChange() == ItemEvent.SELECTED) {
                    int selectedMaNV = Integer.parseInt(cboMaNV.getSelectedItem().toString());
                    // tìm kiếm người quản lí công trình tương ứng với mã nhân viên
                    CongNhan selectedCongNhan = null;
                    for (CongNhan cn : list) {
                        int maCN = cn.getMaCN();
                        if (maCN == selectedMaNV) {
                            selectedCongNhan = cn;
                            break;
                        }
                    }
                    if (selectedCongNhan != null) {
                        // hiển thị tên của người quản lí công trình tương ứng
                        txtTenNV.setText(selectedCongNhan.getTenCN());
                    }
                }
            }
        });
    }

}
