/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLLD_Gui;

import Connection.ConnectSQL;
import QLLD_DAO.CongNhan_DAO;
import QLLD_DTO.CongNhan;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class Thaydoithongtin extends javax.swing.JPanel {

    CongNhan_DAO cnDao = new CongNhan_DAO();
    ConnectSQL cn = new ConnectSQL();

    Connection conn;

    private String username;

    /**
     * Creates new form
     */
    public Thaydoithongtin(String username) {
        initComponents();
        this.username = username;
        checktxtfalse();
        updateData();
//        displayImageOnLabel(1);

    }

    public void setUsername(String username) {
        this.username = username;

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    public String getUsername() {
        return this.username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void checktxtfalse() {

        txtMaCN.enable(false);

    }

    public void checktxttrue() {
        txtCMNDCN.enable(true);
        txtDiaChiCN.enable(true);
        txtHoTenCN.enable(true);
        txtLuongcb.enable(true);
        txtMaCN.enable(true);
        txtPhuCapCN.enable(true);
        txtSDT.enable(true);
        txtngaysinh.enable(true);
        cboChucVu.enable(true);
        cboGioiTinhCN.enable(true);
    }

    public int laymcn() {
        conn = cn.getConnection();

        String query = "Select MaCongNhan as macn from TaiKhoan where TenTaiKhoan=? ";
        try {
            PreparedStatement st = conn.prepareStatement(query);

            st.setString(1, getUsername());
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                return rs.getInt("macn");

            }
        } catch (SQLException ex) {
            Logger.getLogger(HomeMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        return -1;
    }

    private void updateData() {
        CongNhan_DAO ds = new CongNhan_DAO();
        int macn = laymcn();
        List<CongNhan> list = ds.getCongNhanTheoMaCN(macn);
        for (int i = 0; i < list.size(); i++) {
            txtDiaChiCN.setText(list.get(i).getDiaChi());
            txtLuongcb.setText(Double.toString(list.get(i).getLuongcb()));
            txtMaCN.setText(Integer.toString(list.get(i).getMaCN()));
            txtPhuCapCN.setText(Double.toString(list.get(i).getPhuCap()));
            txtSDT.setText(list.get(i).getsDT());
            txtCMNDCN.setText(list.get(i).getCMND());
            txtHoTenCN.setText(list.get(i).getTenCN());
            cboChucVu.setSelectedItem(list.get(i).getChucVu());
            Date date;
            try {
                date = new SimpleDateFormat("yyyy-MM-dd").parse((String) list.get(i).getNgaySinh());
                txtngaysinh.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(Thaydoithongtin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMaNVHC = new javax.swing.JLabel();
        txtMaCN = new javax.swing.JTextField();
        txtHoTenCN = new javax.swing.JTextField();
        lblHoTenNVHC = new javax.swing.JLabel();
        lblCMNDNVHC = new javax.swing.JLabel();
        txtCMNDCN = new javax.swing.JTextField();
        lblNgaySinhNVHC = new javax.swing.JLabel();
        lblGioiTinhNVHC = new javax.swing.JLabel();
        cboGioiTinhCN = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblDiaChiNVHC = new javax.swing.JLabel();
        txtDiaChiCN = new javax.swing.JTextField();
        lblPhuCapNVHC = new javax.swing.JLabel();
        txtngaysinh = new com.toedter.calendar.JDateChooser();
        lblLuongCB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        txtLuongcb = new javax.swing.JTextField();
        txtPhuCapCN = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin công nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        lblMaNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMaNVHC.setText("Mã CN");

        txtMaCN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtHoTenCN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblHoTenNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHoTenNVHC.setText("Họ tên");

        lblCMNDNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCMNDNVHC.setText("CMND");

        txtCMNDCN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblNgaySinhNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNgaySinhNVHC.setText("Ngày sinh");

        lblGioiTinhNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGioiTinhNVHC.setText("Giới tính");

        cboGioiTinhCN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));
        cboGioiTinhCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGioiTinhCNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("SĐT");

        txtSDT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblDiaChiNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiaChiNVHC.setText("Địa chỉ");

        txtDiaChiCN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDiaChiCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiCNActionPerformed(evt);
            }
        });

        lblPhuCapNVHC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPhuCapNVHC.setText("Phụ cấp");

        lblLuongCB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLuongCB.setText("Lương Cơ Bản");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Chức Vụ");

        cboChucVu.enable(false);
        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nhân", "Quản Lý Công Nhân", "Quản Lý Công Trình", "Admin" }));
        cboChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgaySinhNVHC)
                            .addComponent(lblCMNDNVHC))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCMNDCN, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHoTenNVHC)
                            .addComponent(lblMaNVHC))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTenCN)
                            .addComponent(txtMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaChiNVHC)
                            .addComponent(jLabel2)
                            .addComponent(lblGioiTinhNVHC))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(txtDiaChiCN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cboGioiTinhCN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPhuCapNVHC)))
                        .addGap(178, 178, 178))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPhuCapCN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLuongCB)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboChucVu, 0, 300, Short.MAX_VALUE)
                                    .addComponent(txtLuongcb))))
                        .addGap(0, 566, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNVHC)
                            .addComponent(txtMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTenNVHC)
                            .addComponent(txtHoTenCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChiNVHC))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCMNDCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCMNDNVHC)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblGioiTinhNVHC))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txtDiaChiCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboGioiTinhCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhuCapNVHC)
                            .addComponent(txtPhuCapCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgaySinhNVHC)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblLuongCB))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtLuongcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        btnsua.setText("Edit");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btncancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(928, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboGioiTinhCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGioiTinhCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGioiTinhCNActionPerformed

    private void txtDiaChiCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiCNActionPerformed

    private void cboChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChucVuActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed

        int maCN = Integer.parseInt(txtMaCN.getText());
        String tenCN = txtHoTenCN.getText();
        String CMND = txtCMNDCN.getText();
        String sDT = txtSDT.getText();
        double luongcb = Double.parseDouble(txtLuongcb.getText());
        double phuCap = Double.parseDouble(txtPhuCapCN.getText());
        String diaChi = txtDiaChiCN.getText();
        String gioiTinh = cboGioiTinhCN.getSelectedItem().toString();
        String chucVu = cboChucVu.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = txtngaysinh.getDate();
        String ngaySinh = sdf.format(date);
        CongNhan cn = new CongNhan(maCN, tenCN, CMND, sDT, luongcb, phuCap, diaChi, gioiTinh, chucVu, ngaySinh);
        cnDao.update(cn);
        updateData();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        btnsua.setText("Sửa");
        checktxtfalse();
    }//GEN-LAST:event_btncancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsua;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboGioiTinhCN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCMNDNVHC;
    private javax.swing.JLabel lblDiaChiNVHC;
    private javax.swing.JLabel lblGioiTinhNVHC;
    private javax.swing.JLabel lblHoTenNVHC;
    private javax.swing.JLabel lblLuongCB;
    private javax.swing.JLabel lblMaNVHC;
    private javax.swing.JLabel lblNgaySinhNVHC;
    private javax.swing.JLabel lblPhuCapNVHC;
    private javax.swing.JTextField txtCMNDCN;
    private javax.swing.JTextField txtDiaChiCN;
    private javax.swing.JTextField txtHoTenCN;
    private javax.swing.JTextField txtLuongcb;
    private javax.swing.JTextField txtMaCN;
    private javax.swing.JTextField txtPhuCapCN;
    private javax.swing.JTextField txtSDT;
    private com.toedter.calendar.JDateChooser txtngaysinh;
    // End of variables declaration//GEN-END:variables
}
